### ISSUE TITLE
Feature: User can filter recipes by cuisine choice and a specific ingredient. 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#1]
## ⚙️ Feature

Users can filter recipes by cuisine choice and view them on the search page. 
## 📐 Functionality

Users can search for a specific ingredient and type of cuisine and view the results on a different page. 
## 🖼️ Wireframes

![viewlist4](https://user-images.githubusercontent.com/78890855/114631967-7fd80380-9c72-11eb-926b-a660d6fba721.PNG)
![viewlist3](https://user-images.githubusercontent.com/78890855/114631999-8c5c5c00-9c72-11eb-8d3f-e713a5e95b69.PNG)
![viewlist1](https://user-images.githubusercontent.com/78890855/114632001-8ebeb600-9c72-11eb-8b8b-0bef03182c64.PNG)
![viewlist2](https://user-images.githubusercontent.com/78890855/114632013-94b49700-9c72-11eb-9d29-4eb1620c8498.PNG)

## ✅ Task List

- [x] Create a `h1` for the heading "Las Kitchenas" with a `p` "THE HOTTEST DATE NIGHT DESTINATION OF 2020"
- [x] Create a homepage welcoming people to the site that includes a div with the attributes class = "home view" and data-view = "home"
- [x] Create div named `class="tab active"` and add `data-view="home" for Home and `class="tab"` for Search 
- [x] Create a span element with an `i` element linking to font-awesome search icon 
- [x] create a text input with an id = "search" 
- [x] create a select element with name = "cusisineType" and id = "cuisineType"
- [x] add option element with text of the cuisine that will be looked up and the value of that cuisine name. 
- [x] add a button element with id = "search-button"
- [x] Add page that allows search results to pop up on with a div with an attribute of data-view = "search" and class = "view hidden" 
- [x] Add h1 for "Search Results"
- [x] Create html filler for the recipes with a div with the img, h3, and font-awesome star, creating this with DOM creations inside of JS
- [x] Set search and home page result layout to respond to css-responsive layout
- [x] Create a navigation.js and a search.js
- [x] Within search.js create a function named Search with a property of this.lastSearch with a value of an empty array
- [x] Outside the function create a prototype to doSearch and inside issue an HTTP request 
- [x] Outside this prototype create two prototypes for Search for getting last search and to return the last search uri. 
- [x] In navigation.js create a function to change page view with the parameter view for each of the different "pages" adding as you create a new page view. 
- [x] Add a function named form Submit with the parameter event, make sure to prevent default within this
- [x]  This is where search.doSearch method is invoked with the parameters searchForm, cuisisneTypeform, and function with a parameter named resonse
- [x] Within this method create the Dome elements for the search page and append it to the div named "search-results-list
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
