### ISSUE TITLE
Feature: User can view shopping list 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#10]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click on the Shopping List or shopping cart icon to look what they have added to their shopping list. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can view the recipes they added to their shopping list in that specific view when clicking on the shopping cart icon on the menu or the text Shopping List. 
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![shopping web](https://user-images.githubusercontent.com/78890855/115456826-76055180-a1d8-11eb-96fe-624fbc84f7ae.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create a function named makeShoppingList with no parameters
- [x] In navigation.js add a function to create the shopping list page. 
- [x] In this function make sure to remove all children from container then below that using DOM createElement for the heading and ingredients list. Append this to the div with the id "shopping-list" in the html 
- [x] add the function for this to the changePage function. 
- [x] Add the function makeShoppingList if the view equals view = "shopping list" within the function changePage
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
