### ISSUE TITLE
Feature: User can view details of recipe to take them to a page with ingredient list and directions

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Can click on the name of the dish which will take them to an external page with more information on the recipe. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click on the name of the recipe to be taken to a different website with directions and a list of steps to follow when making the dish. 
## 🖼️ Wireframes

![take to another page](https://user-images.githubusercontent.com/78890855/115165192-8c3cd180-a061-11eb-9508-f9ab8379a813.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In search.doSearch method go down to the DOM createElement for the element p, below that add an onclick to the p element 
- [x] In that create a function to open a window to the url for that recipe
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Do the same for favorites function when creating the favorites page 

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
