### ISSUE TITLE
Feature: User can view, add, and remove from Favorites

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#12]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

It will allow the user to add recipes to their favorites and view later. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can click on the star icon, adding it to the favorites page where they can view all their favorites. They can also click on the star icon to unfavorite the item. 

## 🖼️ Wireframes

![favs](https://user-images.githubusercontent.com/78890855/115458424-89192100-a1da-11eb-9ffc-8acec5b2c323.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the heading create a div with the class attribute of "tab" and data-view = "favorites"
- [x] Outside the heading within the div class = "view-container" create a new container div with a nested div with a class = "view hidden" and data-view = "favorites"
- [x] Below that include the header and another nested div with the class "row" and id "favorite-results-list"
- [x] Create a favorites.js and within create a function named Favorites with a property labeled this.recipes with a value of an empty array. 
- [x] Below this function create four Favorites.prototype for adding recipes, removing recipes, list of recipes and getting the recipes of favorites. 
- [x] In navigation.js add a function to create the favorites page, similar to the search page with the DOM create  
- [x] Add this function to the changePage function 
- [x] Create an event listener on the favorite-results-list
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
