### ISSUE TITLE
Feature: User can access favorites and shopping list even if they exit or refresh the page. 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#14]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

The user will be able to come back to see what they have favorited and added to their shopping list when a page is exited or reloaded.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

After leaving the website, refreshing it, or exiting the browser they can come back on the site and still see thier favorites and shopping list. 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Go to favorites.js 
- [x] Inside the Favorites function is where the code for local storage will be added
- [x] Add a variable named favoritesJSON with local storage to the 'ajax-favorites-local-storage'
- [x] AddEventListener to the window before unload event 
- [x] Stringify to the variable favoriteslistJSON
- [x] In callback function stirngify this.recipes with the key of 'ajax-favorites-local-storage'
- [x] Do the same things inside the ShoppingList function on shoppingList.jst
- [x] Add a variable named shoppingJSON with local storage to the 'ajax-shopping-list-local-storage'
- [x] Add an event listener to thewindow for 'beforeunload'
- [x] Strinigify to the variable shoppinglistJSON

- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
