### ISSUE TITLE
Feature: User can save favorites 

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#3]
## ⚙️ Feature

Users can add and remove recipes from their favorites.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

They can click on the star to add to favorites. When on favorites page they can click the star and remove it from favorites. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create HTML for basic formatting of favorite's page including a div class = "container", a nested div with class = "view hidden" and data-view="favorites".
- [ ] 
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
