### ISSUE TITLE
Feature: User can add a recipe to favorites

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can click the star on the recipe container to add the recipe to their favorites, or click it again to remove it from favorites. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Click on the star to add to favorites or click to remove it from favorites. 

## 🖼️ Wireframes

![favorites web](https://user-images.githubusercontent.com/78890855/115162120-78d83900-a056-11eb-8407-0666f4989bab.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] In heading create a nested div within the div class = "tabbed-views" and add an attribute to this new div class = search-form with data-view = "favorites"
- [ ] Within the div add a font awesome icon for favorites. 
- [ ] Then below the heading create a new div with the class = "container", a nested div within with a class = "view hidden" and data-view="favorites"
- [ ] add another nested div below the html for the heading of your favorites page and label this new nested div with an id = "favorite-results-list"
- [ ] In this div with the id "favorite-results-list" we will be adding the information for favorited recipes from JS
- [ ] Create a favorites.js and add a function call 'Favorites' with an empty array for recipes
- [ ] Below create prototypes to add a recipe, remove a recipe, list recipes, and get recipe. 
- [ ] 
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
