### ISSUE TITLE
Feature: User can add ingredients to their shopping cart

### ISSUE THREAD

**Issue by sryuocampo** [sryuocampo/ajax-project#9]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

They can click on the shopping cart icon on the recipe boxes to add or remove it from their cart. 

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Be able to click on the shopping cart icon to add the ingredients to their shopping cart to be printed or looked at later when gathering ingredients for the recipe. Also can click on the icon to remove it from their shopping cart. 

## 🖼️ Wireframes

![shopping web](https://user-images.githubusercontent.com/78890855/115163076-f2265a80-a05b-11eb-945d-1b0fb21ed57b.PNG)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] In the heading create a div with the class attribute of "tab and data-view = "shopping list"
- [x] Outside the heading create a new div with the class attribute of "view-container" a new nesting div within that with the class attribute of "view hidden" and data-view = "shopping-list" within that another nesting div with class attribute of "shopping-heading" 
- [x] After that div create another one with an id "shopping-list", this will be used in JS to push the ingredient list to the shopping page
- [x] Create a shoppingList.js and within create a function named ShoppingList with an empty array named this.recipes
- [x] Outside this function create ShopingList prototype for the methods to add a recipe, remove a recipe, list ingredients and get recipe. 
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
